# Generated by Django 3.1.2 on 2020-11-02 12:24

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=file.models.get_file_path)),
                ('filename', models.CharField(max_length=64, null=True)),
                ('hex_name', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
