# Generated by Django 3.1.2 on 2020-11-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='color',
            field=models.CharField(default='f8f1ba', max_length=10),
        ),
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='f8f1ba', max_length=10),
        ),
    ]
