# Generated by Django 3.1.2 on 2020-11-12 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_auto_20201110_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('type_index', models.IntegerField()),
                ('content', models.TextField()),
                ('color', models.CharField(default='f8f1ba', max_length=10)),
                ('user_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='type_index',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Time_Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('capsule_list', models.ManyToManyField(related_name='time_machine', to='board.Capsule')),
            ],
        ),
    ]
