# Generated by Django 3.1.2 on 2020-11-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20201112_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='max_tm_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='time_machine',
            name='tm_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
